version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: go_pg
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: appdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: go_api
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  pgdata:
